### ISSUE TITLE
Please give proper photo credit

### ISSUE THREAD

**Issue by ahmetb** [eon01/kubernetes-workshop#5]
The illustrations you put to this repository say 

> (photo credit:medium.com/google-cloud)

1. they don't even link to a proper post
2. the post you got it from has my name but you dropped it.

smh

**Comment by ahmetb** [comment]
Since you're not clearly able to do this, please credit each drawing as:

> Illustration from [Ahmet Alp Balkan](https://twitter.com/ahmetb) via [Medium](https://medium.com/google-cloud/kubernetes-nodeport-vs-loadbalancer-vs-ingress-when-should-i-use-what-922f010849e0).

**Comment by eon01** [comment]
Sure thing Ahmet. I found this after a Google Image search, and copied it from Google Cloud Medium publication but not in your post (you can make a good search). 

However, I don't have any problem attributing the original work to its original author instead of its original publication. In both cases, saying that "I'm clearly not able to do this" is wrong and compulsive.
